# alias g := generate

set shell := ["bash", "-uc"]

subLine := "http://handyMini:3001/c53248f264d9997/download/collection/main?target=URI"

policy-filter := "@🌐Proxy@⚡UrlTest-~^(?!.*(aote|流量|到期|过滤|官网|Rfchost(.+)Anytls|kooya|\\]日本)).*$@💬AI-~^(?!.*(流量|到期|过滤|官网)).*$@🚀LowLatency-~^(?!.*(流量|到期|过滤|官网)).*$"

alias b := tun

default:
  @just --list

clean:
  rm -f ./*.json

realdns:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp --template '../substore/real-dns.json' -o config.json

realdns-log:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp --template '../substore/real-dns.json' --log-file box.log -o config.json

tun:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp -o config.json

windows-tun:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp --windows --log-file '' -o windows-tun.json

singb:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --log-file '' --icmp -o singb.json

notun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --icmp -o inotun.json

imx-notun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --icmp --mixed-port 2134 -o imx-notun.json

nout-itun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --icmp --log-file 'box.log' -o nout-itun.json

icmp-tun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --icmp -o icmp-tun.json

linux-tun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --linux -o linux-tun.json

android-tun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --android -o android-tun.json
