# alias g := generate

set shell := ["bash", "-uc"]

subLine := "http://fngo:3001/c53248f264d9997/download/collection/main?target=URI"

policy-filter := '@🌐Proxy@⚡UrlTest-~^(?!.*(kooya|流量|套餐|重置)).*$@💬AI@🚀LowLatency@🎮Steam'

alias b := tun

default:
  @just --list

clean:
  rm -f ./*.json

realdns:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp --template '../substore/real-dns.json' -o config.json

realdns-log:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp --template '../substore/real-dns.json' --log-file box.log -o config.json

tun:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp -o config.json

windows-tun:
  node base.js -s '{{subLine}}' -p '{{policy-filter}}' --tun --icmp --windows -o windows-tun.json

singb:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --icmp -o singb.json

lreal-notun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --icmp --template '../substore/real-dns.json' -o lreal-notun.json

notun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --icmp -o inotun.json

imx-notun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --icmp --mixed-port 2134 -o imx-notun.json

nout-itun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --icmp --log-file 'box.log' -o nout-itun.json

icmp-tun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --icmp -o icmp-tun.json

linux-tun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --linux -o linux-tun.json

linux-tun-ipv6:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --linux --ipv6 -o linux-tun-ipv6.json

android-tun:
  node base.js --subscribe-link '{{subLine}}' --policy-filter '{{policy-filter}}' --tun --android -o android-tun.json
